version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'

  system-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.tests
    depends_on:
      - web-app
