name: Run system tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build compose
        run: docker-compose up -d
      - name: Run tests
        run: docker-compose up tests
